name = "clanka-api"
main = "src/index.ts"
compatibility_date = "2024-02-08"

# Secret bindings (set with `npx wrangler secret put <NAME>`)
# - ADMIN_KEY
# - GITHUB_TOKEN

[vars]
# Public variables only
ENVIRONMENT = "production"

[[kv_namespaces]]
binding = "CLANKA_STATE"
id = "39b3f694feb347fa84dcc3cd9f1861c6"
